# Generated by Django 2.2.17 on 2021-04-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210427_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sale',
            field=models.FloatField(default=0),
        ),
    ]
