# Generated by Django 2.2.17 on 2021-04-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_category_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sale',
            field=models.FloatField(default=0, max_length=1.0),
        ),
    ]
