# Generated by Django 2.2.17 on 2021-04-27 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210427_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sale',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
