# Generated by Django 2.2.17 on 2021-04-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='users',
            name='activation_key_registered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
