# Generated by Django 2.2.17 on 2021-04-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_usersprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='locate',
            field=models.TextField(blank=True, verbose_name='страна'),
        ),
    ]
