# Generated by Django 2.2.17 on 2021-04-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_usersprofile_locate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'мужской'), ('W', 'женский')], max_length=1, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='locate',
            field=models.CharField(blank=True, max_length=3, verbose_name='страна'),
        ),
    ]
